name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - name: Cargo check
        run: cargo check --workspace
  checks_old:
    name: Check 1.37.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.37.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - name: Delete Cargo.lock
        run: rm Cargo.lock
      - name: Cargo check
        run: cargo check --all
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo doc
        run: cargo doc --workspace --no-deps
      - name: Cargo clippy
        run: cargo clippy --workspace --tests -- -D warnings
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: [checks, lints]
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - name: Cargo test
        run: cargo test --workspace
  tests_old:
    name: Test 1.37.0
    runs-on: ubuntu-latest
    needs: [checks, lints]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.37.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - name: Delete Cargo.lock
        run: rm Cargo.lock
      - name: Cargo test
        run: cargo test --all
